/*
Name: Joseph Park * Raymond Lam, Group 13
Date: September 2, 2014
Assignment: Lab 3, Problem 4.24
Input: No input
Process: Processes the Monty Hall Paradox 1000 times with randomly generated doors and choices
Output: Outputs how many times the player won if they switched and how many times if the player stays
*/
package lab3_p4.pkg24;
import java.util.Random;
import java.util.Scanner;
public class Lab3_P424 {
    static Random Rand = new Random();
    static Scanner In = new Scanner(System.in);
    static final int NUMBER = 1000;
    public static void main(String[] args) {
        int switchCount = 0, stayCount = 0;
        int doorList[] = PlaceCar();
        int player, host;
        for(int i = 0; i < NUMBER; i++){
            player = PlayerPick();
            host = HostPick(player,doorList);
            Display(player,host);
            if(AskSwitch(player,host) == 0){
                player = SetSwitch(player,host);
                if(CheckWin(player,doorList))
                    switchCount++;
            }
            else
                if(CheckWin(player,doorList))
                    stayCount++;
        }
        System.out.print("\nSwitch Wins: " + switchCount + "\nStay Wins: " + stayCount +"\n");
    }
    static int[] PlaceCar(){
        int carDoor = Rand.nextInt(3);
        int doorList[] = {0,0,0};
        doorList[carDoor] = 1;
        return doorList;
    }
    static int PlayerPick(){
        return Rand.nextInt(3);
    }
    static int HostPick(int playerDoor, int[] doorList){
        int hostPick;
        while(true){
            hostPick = Rand.nextInt(3);
            if(hostPick != playerDoor && doorList[hostPick] != 1){
                return hostPick;
            } 
        }
    }
    static int AskSwitch(int playerChoice, int hostChoice){
        return Rand.nextInt(2);
    }
    static int SetSwitch(int playerChoice, int hostChoice){
        for(int i = 0; i < 3; i++){
            if(i != playerChoice && i != hostChoice)
                return i;
        }
        return -1;
    }
    static boolean CheckWin(int playerChoice, int[] doorList){
        return doorList[playerChoice] == 1;
    }
    static void Display(int player, int host){
        System.out.print("\nPlayer Choice: " + (player + 1) + "\nHost Choice: " + (host + 1));
    }
}
/*
run:

Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 1
Host Choice: 2
Player Choice: 2
Host Choice: 1
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 2
Player Choice: 3
Host Choice: 1
Player Choice: 1
Host Choice: 2
Player Choice: 3
Host Choice: 1
Switch Wins: 364
Stay Wins: 147
BUILD SUCCESSFUL (total time: 0 seconds)

*/